### ISSUE TITLE
Plugin is not working on my installation of WP

### ISSUE THREAD

**Issue by SieBer15** [VasylTech/advanced-access-manager#2]
I not see any menu on the left sidebar. See my attached file...

![schermafbeelding 2015-11-27 om 13 58 13](https://cloud.githubusercontent.com/assets/12611416/11441706/f7df18bc-950e-11e5-8eaf-874beb25ee78.png)

**Comment by VasylTech** [comment]
Thank you for your feedback.

From the screenshot I can tell that JavaScript for AAM is not initialized properly. Usually this is a case when either your custom theme or some of the installed plugins cause interference with AAM. Most likely you have some JavaScript errors on your page too,
You can send us your website credentials so we check it for u. Our email vasyl@vasyltech.com

Regards,
Vastly

**Comment by SieBer15** [comment]
Sorry I was already warned for that. I wanted to use your plugin together with the MainWP plugin, but they say it is obvious there will be errors when using their plugin with other plugins.

Thanks!

**Comment by VasylTech** [comment]
This is a very common problem among WordPress plugins. A lot of developers violate the WordPress hooks and print JavaScript or CSS libraries even when they are not used. 

If you familiar with PHP you can find out that AAM prints supportive JavaScript and css libraries only when you are on the AAM page. That is why AAM never breaks other plugins.
