### ISSUE TITLE
SSL causes issue

### ISSUE THREAD

**Issue by Yoav1987** [VasylTech/advanced-access-manager#3]
![aam-ssl-issue](https://cloud.githubusercontent.com/assets/4377522/11494252/637aeef0-9809-11e5-9e7b-26bb545f612f.png)

As you see, when the website is secured (HTTPS), the AAM administration doesn't load until you click on the shield because somewhere in the plugin file is not secured... It could only be some http:// URL which has to be // to prevent such issue.

**Comment by Yoav1987** [comment]
For example: https://github.com/VasylTech/advanced-access-manager/blob/master/Application/Core/Server.php

 /**
     * Server endpoint
     */
    const SERVER_URL = 'http://rest.vasyltech.com/v1';

Should be 

 /**
     * Server endpoint
     */
    const SERVER_URL = '//rest.vasyltech.com/v1';

And your website must be SSL friendly...

**Comment by VasylTech** [comment]
Hi Yoav1987,

Thank you for your feedback. We are totally agree with you that vasyltech.com should have SSL cert installed and it is still on our todo list. It is a low priority task for us because we do not deal with any sensitive data but we have plan to have it installed within next few weeks.

Thank you for the interest in AAM.
Vasyl

**Comment by Yoav1987** [comment]
You didn't understand me. See the screenshot:

![aam-ssl2](https://cloud.githubusercontent.com/assets/4377522/11498657/694ba0e8-9829-11e5-9739-61f06249170a.png)

As you can see, the AAM administration doesn't loading up because my website is secured. So, until your plugin, is not fully compatible with SSL, I won't be able to open it... 

It's mean that every HTTPS website cannot see the AAM administration. Hope I was clearer.

**Comment by VasylTech** [comment]
Oh. Got you. Thank you for your feedback. I'm checking this right now.

Regards,
Vasyl

**Comment by Yoav1987** [comment]
Then, if you want a free SSL setup, check CloudFlare. Easy peasy to use :)

**Comment by VasylTech** [comment]
Thank you. I'll look closer into it.
